INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('1', 'ابتزاز', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('2', 'اتلاف', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('3', 'اجهاض', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('4', 'احتجاز بدون وجه حق', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('5', 'اختلاس مال عام', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('6', 'اخفاء اشياء مسروقة', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('7', 'ادارة منشئة للتصنيع السلاح', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('8', 'استعمال قسوة', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('9', 'استيلاء', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('10', 'اصابة خطا', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('11', 'اصابة متهم', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('12', 'اضراب عن العمل ', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('13', 'اضرار مال عام', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('14', 'اغتصاب', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('15', 'اكراه علي توقيع', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('16', 'الاتجار في المواد المخدرة', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('17', 'الاتجار في المواد المخدرة وتزيف عملة', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('18', 'انتحار', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('19', 'انتحال صفة ', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('20', 'انضمام الي جماعه محظورة', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('21', 'اهمال شركة مياة الشرب', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('22', 'اهمال طبي', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('23', 'بطلجة ', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('24', 'تبديد', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('25', 'تحرش', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('26', 'تربح', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('27', 'تزوير', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('28', 'تزيف عملة', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('29', 'تشهير', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('30', 'تشهير عن طريق الانترنت', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('31', 'تظاهر', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('32', 'تعاطي مواد مخدرة', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('33', 'تعدي بالضرب ', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('34', 'تعدي جنسي ', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('35', 'تعدي علي أطفال بالدار', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('36', 'تعدي علي موظف عام', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('37', 'جرائم انتخابية', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('38', 'حريق', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('39', 'حيازة سلعة تمونية ', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('40', 'خطف', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('41', 'دعارة', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('42', 'رشوة', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('43', 'زنا', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('44', 'سب وقذف', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('45', 'سرقة', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('46', 'سرقة بالاكراه', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('47', 'سرقة دواب', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('48', 'سرقة سيارة', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('49', 'سرقة كابلات', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('50', 'سرقة مهمات', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('51', 'سرقة مواد بترولية', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('52', 'سرقة هاتف', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('53', 'سلاح ابيض واحداث اصابة', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('54', 'سلاح أبيض وتعاطي حشيش', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('55', 'سلاح ناري', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('56', 'سلاح ناري وبلطجة', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('57', 'سلاح ناري وذخيرة', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('58', 'شروع في سرقة', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('59', 'شروع في سرقة بالاكراه', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('60', 'شروع في قتل', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('61', 'شروع في قتل و سلاح ناري', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('62', 'شروع في هتك عرض', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('63', 'شكوي مستشار / تهديد', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('64', 'ضرب', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('65', 'ضرب افضي الي موت', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('66', 'ضرب واحداث اصابة', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('67', 'طرح أغذية منتهية الصلاحية ( غش تجاري )', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('68', 'عاهه', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('69', 'عثور علي سيارة ', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('70', 'عدوان علي مال العام', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('71', 'فعل فاضح ومواد مخدرة', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('72', 'قتل', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('73', 'قتل خطا وهتك عرض', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('74', 'مادة', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('75', 'مشاجره', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('76', 'مقاومة سلطات', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('77', 'مقاومة سلطات وتمكين من الهرب', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('78', 'مواد مخدرة ومقامة سلطات', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('79', 'نصب', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('80', 'نصب واحتيال', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('81', 'نصب وسرقة', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('82', 'هتك عرض', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('83', 'وفاة', CURRENT_TIMESTAMP, NULL, '1', '0');
INSERT INTO `cj_investigation`.`charges` (`id_charges`, `name`, `createdate`, `updatedate`, `status`, `deleted`) VALUES ('84', 'وفاة مسجون', CURRENT_TIMESTAMP, NULL, '1', '0');
